var QUOTES = [
"Use the metal part of your seat belt to open beers while driving!",
"Armed violence is no mature way to resolve conflict. You should sit together and talk things out like adults.",
"You shouldn't smoke. You may not care now, but you will, once you slowly die one of the most miserable deaths.",
"Don't judge other people when you haven't been in their situation. And even then!",
"Whether one has quick intelligence or needs time to think things over is not important. Wisdom comes from thinking selflessly.",
"Among one's affairs there should not be more than two or three matters of great concern.",
"Don't focus only on the negative aspects of things!",
"If you made a mistake, don't hesitate to correct yourself!",
"One should make his decisions within the space of seven breaths.",
"Endure suffering!",
"Live in the moment!",
"Do the things you do with focus, dedication and passion!",
"Even good things can be carried too far.",
"When there is something to be said, it is better if it is said right away.",
"Live with integrity!",
"Don't care too much what others think!",
"Don't make decisions when you're angry. Don't make promises when you’re happy.",
"Travel! Explore!",
"Don't give up what you want most for what you want now!",
"Value honest criticism about your gameplay and also about every other aspect of your person!",
"Wait 24 hours before getting mad and reacting about anything!",
"Respect yourself!",
"Be your friend, not your judge!",
"Spend time in nature between matches!",
"Exercise between matches! And exercise more in general! Seriously!",
"Care more about nutrition! Statistics suggests that you know way too little about it, considering how important it is.",
"Volunteer! Give! Share! Contribute!",
"Care about your family, friends and your partner(s)!",
"Take enough time to sleep, relax and meditate!",
"Do some spiritual stuff! The internal world is as interesting as the external one.",
"You don't have to have a dream. You can also just embrace going with the flow.",
"Happiness is like an orgasm: If you think about it too much, it goes away.",
"Be hard on your opinions!",
"Teach! Inspire!",
"Make others happy!",
"Define yourself by what you love, not what you hate!",
"Respect people who have less power than you! (Respect everyone in general!)",
"Don't panic! Don't rush!",
"Hang out with people who are the way you want to be! Inspiration is a very powerful force to shape your character.",
"Negative experiences are part of life as well. No need to make a fuss out of them.",
"Go your own path!",
"Do not encourage things to get worse!",
"There will always be people who have it shittier than you.",
"Great things take time! Be patient and persistent!",
"Be greatful for what you have!",
"Nothing lasts.",
"Let go!",
"The world is not necessarily just. This game is though.",
"Take responsibility for your actions.",
"Chill!",
"You can't make anyone love you.",
"Who if not you? When if not now?",
"Try not to take anything personally. No one thinks about you as much as you do.",
"Don't be so full of yourself. You're just you.",
"All evil is potential vitality in need of transformation.",
"All of you is worth something if you will only own it.",
"No one can make the big decisions for you.",
"Nothing is fully under your control.",
"All important decisions must be made on the basis of insufficient data.",
"We must learn the power of living with our helplessness.",
"You are free to do whatever you like. You need only face the consequences.",
"Love is always stronger than fear. Always choose on the basis of love.",
"This, too, shall pass.",
"If you're depressed, you're living in the past. If you're anxious, you're living in the future. If you're content, you're accepting the present.",
"Commit yourself to personal growth!",
"Whenever something happens that makes you sad, ask yourself whether you’d still care about it when you’re ninety.",
"Be persistent. When knowledge and ability aren’t enough, be persistent.",
"Life is scary. Get used to it. There are no magical fixes. It’s all up to you.",
"Never stop learning!",
"Always look at the world with new eyes!",
"Learn to say No.",
"The truth should be handed to people like a warm coat, not slapped into their faces like a wet towel.",
"Be yourself!",
"Learn from other people's mistakes, you don't have enough time in your life to make them all yourself.",
"Say what you mean and mean what you say.",
"Instead of focusing on what you think of people, find out what you can learn from them.",
"What's the worst that can happen?",
"Sometimes you just have to do the next-right thing.",
"No one builds a house. You put brick by brick.",
"It's easier to get forgiveness than permission.",
"No matter how far you've gone down the wrong road, turn back.",
"What will you wish you would have done in 20 years?",
"Don't be an idiot!",
"Don't let a video game dictate your life!",
"Everything changes.",
"Act yourself into a feeling, don't feel yourself into an action.",
"Only boring people get bored.",
"When you don't know the answer, just ask elaborate follow up questions to their questions. Or criticize their grammar.",
"If you cut a face lengthwise, urinate on it, and trample on it with straw sandals, it is said that the skin will come off. This was heard by the priest Gyojaku when he was in Kyoto. It is information to be treasured. (Actual quote from Hagakure, the book of the Samurai)",
"When losing an argument, always move the conversation to looking at the bigger picture.",
"Don't listen to other people's advice! Think for yourself!",
"Prevent cake from getting dry by eating it all at once!",
"Be honest!"
];

//sources: hagakure, common knowledge, http://inktank.fi/28-of-the-best-pieces-of-advice-about-life-youll-ever-read/ hackschooling, tim minchin, http://waitbutwhy.com/table/best-advice, https://questionofmindfulness.wordpress.com/2009/04/08/sheldon-kopps-eschatological-laundry-list/, friends, http://www.boredpanda.com/shitty-life-pro-tips/?afterlogin=savecommentvote&comment=997233&score=1
